# Generated by Django 4.2.4 on 2023-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="number",
            field=models.IntegerField(max_length=50),
        ),
    ]
